/*
 * This file was autogenerated by TinyMPC on Tue Apr  8 09:32:31 2025
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
