[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tinympc_sam_schoedel"
version = "0.0.13"
authors = [
  { name="Khai Nguyen", email="khai.nx1201@gmail.com" },
  { name="Sam Schoedel", email="seschoedel@gmail.com" },
]
description = "Python wrapper for TinyMPC"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = {file = "LICENSE"}

[project.urls]
Homepage = "https://tinympc.org"

[tool.setuptools_scm]

[tool.black]
line-length = 88
target-version = ['py39']