/*
 * This file was autogenerated by TinyMPC on Tue Dec  5 22:20:27 2023
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_data_solver;

#ifdef __cplusplus
}
#endif
